### ISSUE TITLE
Canonical Snowflake provider

### ISSUE THREAD

**Issue by sjauld** [Preston4tw/terraform-provider-snowflake#14]
It seems like there are three active providers:

- https://github.com/chanzuckerberg/terraform-provider-snowflake
- https://github.com/Preston4tw/terraform-provider-snowflake
- https://github.com/ShopRunner/terraform-provider-snowflake

Any chance of the three of you combining efforts? I want to contribute but first I'll need to work out which one is close enough to what I need (all three are missing different bits and pieces).

**Comment by Preston4tw** [comment]
I work at Snowflake.

This project was briefly used internally at Snowflake by the security team as part of https://github.com/snowflakedb/SnowAlert/ and was deprecated in favor of just straight SQL and python scripts. The security team discussed having the connectors team adopt and officially support it, but there hasn't been enough customer interest. This repo is currently abandoned, so neither me nor this repo are good candidates for taking point on a combined effort.

Either project is welcome to wholesale copy and adapt everything in this repo.

**Comment by sjauld** [comment]
Thanks for the info! 1 down, 2 to go!

**Comment by sjauld** [comment]
Just for posterity, I think https://github.com/chanzuckerberg/terraform-provider-snowflake is definitely the way to go. I'll close this issue out.
